version: '3.0'
services:
  crawler_game:
    image: crawler:p_league
    hostname: "game"
    command: pipenv run celery -A stats.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h --timezone=Asia/Taipei -Q game
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - p_league

  crawler_year:
    image: crawler:p_league
    hostname: "year"
    command: pipenv run celery -A stats.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h --timezone=Asia/Taipei -Q year
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - p_league
networks:
  p_league:
    # 加入已經存在的網路
    external: true