version: '3.0'
services:
  crawler_game:
    image: crawler:p_league
    hostname: "game"
    command: pipenv run celery -A stats.tasks.worker worker --loglevel=info --concurrency=1  --hostname=%h -Q game
    restart: always
    environment:
      - TZ=Asia/Taipei
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.crawler_game == true]
    networks:
      - my_network

  crawler_year:
    image: crawler:p_league
    hostname: "year"
    command: pipenv run celery -A stats.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h -Q year
    restart: always
    environment:
      - TZ=Asia/Taipei
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.crawler_year == true]
    networks:
      - my_network
networks:
  my_network:
    # 加入已經存在的網路
    external: true