version: '3.0'
services: 
  api:
    image: joshua881117/api:p_league
    ports:
      - 8888:8888
    hostname: "api"
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    external: true